/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author User
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() { // CONSTRUTOR
        initComponents();
        painelCalc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        lblCalcImg = new javax.swing.JLabel();
        painelCalc = new javax.swing.JPanel();
        lblResDivValor = new javax.swing.JLabel();
        lblResDiv = new javax.swing.JLabel();
        lblEleCubo = new javax.swing.JLabel();
        lblRaizQ = new javax.swing.JLabel();
        lblRaizC = new javax.swing.JLabel();
        lblValAbs = new javax.swing.JLabel();
        lblEleCuboValor = new javax.swing.JLabel();
        lblRaizQValor = new javax.swing.JLabel();
        lblRaizCValor = new javax.swing.JLabel();
        lblValAbsValor = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Super Calculadora");

        jLabel2.setText("Informe um valor:");

        txtNum.setModel(new javax.swing.SpinnerNumberModel(1, -50, 50, 1));

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculator-pepicons-24x24.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblCalcImg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCalcImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculator-flat-144x180.png"))); // NOI18N

        lblResDivValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblResDivValor.setForeground(new java.awt.Color(51, 102, 255));
        lblResDivValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResDivValor.setText("0");

        lblResDiv.setText("Resto da Divisão por 2:");

        lblEleCubo.setText("Elevado ao Cubo:");

        lblRaizQ.setText("Raiz Quadrada:");

        lblRaizC.setText("Raiz Cúbica:");

        lblValAbs.setText("Valor Absoluto:");

        lblEleCuboValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEleCuboValor.setForeground(new java.awt.Color(51, 102, 255));
        lblEleCuboValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEleCuboValor.setText("0");

        lblRaizQValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRaizQValor.setForeground(new java.awt.Color(51, 102, 255));
        lblRaizQValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRaizQValor.setText("0");

        lblRaizCValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRaizCValor.setForeground(new java.awt.Color(51, 102, 255));
        lblRaizCValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRaizCValor.setText("0");

        lblValAbsValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValAbsValor.setForeground(new java.awt.Color(51, 102, 255));
        lblValAbsValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValAbsValor.setText("0");

        javax.swing.GroupLayout painelCalcLayout = new javax.swing.GroupLayout(painelCalc);
        painelCalc.setLayout(painelCalcLayout);
        painelCalcLayout.setHorizontalGroup(
            painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValAbs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResDiv, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEleCubo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRaizQ, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRaizC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEleCuboValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRaizQValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRaizCValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValAbsValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResDivValor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12))
        );
        painelCalcLayout.setVerticalGroup(
            painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResDiv)
                    .addComponent(lblResDivValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEleCubo)
                    .addComponent(lblEleCuboValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaizQ)
                    .addComponent(lblRaizQValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaizC)
                    .addComponent(lblRaizCValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValAbs)
                    .addComponent(lblValAbsValor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(lblCalcImg))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnCalcular)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCalcImg)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        painelCalc.setVisible(true);
        
        int valor = Integer.parseInt(txtNum.getValue().toString());
        
        //resto da divisão
        int resDiv = valor % 2;
        lblResDivValor.setText(Integer.toString(resDiv));
        
        //elevado ao cubo
        double eleCubo = Math.pow(valor, 3);
        lblEleCuboValor.setText(String.format("%.0f", eleCubo));
        
        //raiz quadrada
        double raizQ = Math.sqrt(valor);
        lblRaizQValor.setText(String.format("%.2f", raizQ));
        
        //raiz cubica
        double raizC = Math.cbrt(valor);
        lblRaizCValor.setText(String.format("%.2f", raizC));
        
        //valor absoluto
        int valAbs = Math.abs(valor);
        lblValAbsValor.setText(Integer.toString(valAbs));
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCalcImg;
    private javax.swing.JLabel lblEleCubo;
    private javax.swing.JLabel lblEleCuboValor;
    private javax.swing.JLabel lblRaizC;
    private javax.swing.JLabel lblRaizCValor;
    private javax.swing.JLabel lblRaizQ;
    private javax.swing.JLabel lblRaizQValor;
    private javax.swing.JLabel lblResDiv;
    private javax.swing.JLabel lblResDivValor;
    private javax.swing.JLabel lblValAbs;
    private javax.swing.JLabel lblValAbsValor;
    private javax.swing.JPanel painelCalc;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration//GEN-END:variables
}
